issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - SA1019
  exclude-files:
    - avi/resource_avi_rest_dependants.go

  exclude-rules:
    - linters:
        - errcheck
      text: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema:ForceNew|Set
    - linters:
        - errcheck
      text: fmt:.*
    - linters:
        - errcheck
      text: io:Close

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    # - goimports
    - gosimple
    - govet
    - ineffassign
    - nakedret
    - misspell
    - staticcheck
    - typecheck
    - unused
    - unconvert
    - vet
    - vetshadow
