version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt

linters:
  default: none
  enable:
    #- errcheck
    - ineffassign
    - nakedret
    #- misspell
    #- staticcheck
    #- govet
  settings:
    errcheck:
      exclude-functions:
        - fmt.Print
        - fmt.Printf
        - fmt.Println
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - io.Close
    govet:
      enable:
        - shadow
